language: python
python:
  - "3.5.2"
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
services:
  - mongodb
install:
  - pip install -e .[tests]
  - pip install coveralls
script: green -r
after_success:
  coveralls